# Generated by Django 4.2.13 on 2024-06-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=32, unique=True)),
                ("account_type", models.CharField(max_length=50)),
                ("opening_date", models.DateField()),
                ("account_status", models.CharField(max_length=50)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "overdraft_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("bank_id", models.AutoField(primary_key=True, serialize=False)),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_address", models.CharField(max_length=255)),
                ("established_date", models.DateField()),
                ("operational_status", models.CharField(max_length=50)),
                ("contact_phone", models.CharField(max_length=50)),
                ("contact_email", models.EmailField(max_length=254)),
                ("service_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_gender", models.CharField(max_length=10)),
                ("birth_date", models.DateField()),
                ("occupation", models.CharField(max_length=100)),
                ("contact_address", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=50)),
                ("contact_email", models.EmailField(max_length=254)),
                ("customer_level", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("department_name", models.CharField(max_length=100)),
                ("responsibilities", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=50)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.bank"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=50)),
                ("email_address", models.EmailField(max_length=254)),
                ("hire_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=15)),
                ("performance_rating", models.CharField(max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="bank.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("disbursement_date", models.DateField()),
                ("due_date", models.DateField()),
                ("loan_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("loan_status", models.CharField(max_length=50)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manages",
                to="bank.employee",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
            ),
        ),
    ]
