# Generated by Django 4.2.13 on 2024-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_account_bank_customer_department_employee_loan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bank_id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
