# Generated by Django 4.2.13 on 2024-06-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0006_alter_account_customer_alter_department_bank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank.customer",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="bank",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="bank.bank"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manages",
                to="bank.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="bank.department",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
            ),
        ),
    ]
