# Generated by Django 4.2.13 on 2024-06-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0007_alter_account_customer_alter_department_bank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="customer",
        ),
        migrations.AddField(
            model_name="loan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank.account",
            ),
        ),
    ]
