# Generated by Django 4.2.13 on 2024-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0008_remove_loan_customer_loan_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="photo_filename",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
